apiVersion: v1
kind: Service
metadata:
  namespace: ${NAMESPACE}
  name: otel-collector-service

apiVersion: v1
kind: Service
metadata:
  namespace: ${NAMESPACE}
  name: otel-collector-service
spec:
  type: ClusterIP
  selector:
    app: garion-otel-collector
  ports:
    - port: 80
      targetPort: 8080