apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: garion-1
  name: garion-grafana-deployment
  labels:
    app: garion-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: garion-grafana
  template:
    metadata:
      labels:
        app: garion-grafana
    spec:
      containers:
      - name: garion-grafana
        image: 144.17.92.12:5000/garion-1/grafana:1
        ports:
        - containerPort: 3000
        # env:
        # - name: COLLECTOR_URL
        #   value: http://otel-collector-service:4317/
        # - name: ASPNETCORE_ENVIRONMENT
        #   value: Development
        # - name: db
        #   value: server=grafana-db-service;user id=postgres;database=gariondb;password=password