apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: ${NAMESPACE}
  name: garion-blazor-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: ${GITHUB_RUN_ID}.garion-telemetry-ts.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: garion-blazor-service
            port:
              number: 8080
  - host: ${GITHUB_RUN_ID}.garion-kube.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: garion-blazor-service
            port:
              number: 8080