apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: ${NAMESPACE}
  name: garion-blazor-ingress
  annotations:
    cert-manager.io/cluster-issuer: cert-manager-webhook-duckdns-garion-production
spec:
  tls:  
  - hosts:    
  - ${GITHUB_RUN_ID}.garion-telemetry-ts.duckdns.org
  secretName: garion-kube-tls-production
  ingressClassName: nginx
  rules:
  - host: ${GITHUB_RUN_ID}.garion-telemetry-ts.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: garion-blazor-service
            port:
              number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: ${NAMESPACE}
  name: garion-blazor-ingress
  annotations:
    cert-manager.io/cluster-issuer: cert-manager-webhook-duckdns-garion-production
spec:
  tls:  
  - hosts:    
  - ${GITHUB_RUN_ID}.garion-kube.duckdns.org
  secretName: garion-kube-tls-production
  ingressClassName: nginx
  rules:
  - host: ${GITHUB_RUN_ID}.garion-kube.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: garion-blazor-service
            port:
              number: 8080