{
 "title": "Garion Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Active Connections (Kestrel)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"metrics\", __name__=\"kestrel_active_connections\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "(6h) Purchased Tickets/Second",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(purchases_count_total{job=\"metrics\"}[6h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# Home Page Loads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(homepage_count_total{job=\"metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% Users Purchased Ticket",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(purchases_count_total{job=\"metrics\"}) / sum(homepage_count_total{job=\"metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Connections (24h)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(kestrel_active_connections{job=\"metrics\"}[1d])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}