{
 "title": "Garion Telemetry",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Metrics",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki (Custom Traces)",
   "type": "logs",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"FirstTrace\"}"
    }
   ]
  },
  {
   "title": "Blackbox",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{job=\"blackbox\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\"} | json | line_format \"{{.body}}\" |~ \".*garion-logger.*\""
    }
   ]
  }
 ]
}