name: backup database
on:
    - workflow_dispatch
jobs:
    backup:
        runs-on: self-hosted
        steps:
            - name: backup
              run: |
                CONTAINER_NAME=$(kubectl -n garion-1 get pods --no-headers -o custom-columns=":metadata.name" | grep "blazor-web-db-deployment")
                kubectl exec -n garion-1 -it $CONTAINER_NAME -- \
                  pg_dumpall -c -U postgres > dump_postgres.sql \
                  > /home/garion/dump.sql
                