name: Pull Request Environment
on:
  pull_request:
    types: [opened]
jobs:
  deploy-to-kubernetes:
    runs-on: self-hosted
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
      - name: Deploy Kubernetes Environment
        run: |
          export PULL_REQUEST_ID=${{ github.event.pull_request.number}}
          kubectl create namespace garion-pr-$PULL_REQUEST_ID